ControleEstoque/Controllers/OntController.cs
using ControleEstoque.Filters;
using ControleEstoque.Models;
using ControleEstoque.Repositorio;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace ControleEstoque.Controllers
{
    //Função para ativar o filtro e diferenciar se é um usuario padrão ou admin e colocar suas restrições
    [PaginaParaUsuarioLogado]
    public class OntController : Controller
    {
        private readonly IOntRepositorio _ontRepositorio;
        public OntController(IOntRepositorio ontRepositorio)
        {
            _ontRepositorio = ontRepositorio;
        }
        public IActionResult Index()
        {
            List<OntModel> onts = _ontRepositorio.Buscartodos();
            return View(onts);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            OntModel ont = _ontRepositorio.ListarPorId(id);
            return View(ont);
        }

        public IActionResult detalhes(int id)
        {
            OntModel ont = _ontRepositorio.ListarPorId(id);
            return View(ont);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            OntModel ont = _ontRepositorio.ListarPorId(id);
            return View(ont);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                //Chamando o método Apagar da OntRepositorio
                bool apagado = _ontRepositorio.Apagar(id);

                if(apagado)
                {
                    TempData["MensagemSucesso"] = "Produto apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu produto!";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu produto, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(OntModel ont)
        {
            //Chamando o método Adicionar da OntRepositorio

            try
            {
                if (ModelState.IsValid)
                {
                    _ontRepositorio.Adicionar(ont);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(ont);
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu produto, tente novamente, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
         
        }

        [HttpPost]
        public IActionResult Alterar(OntModel ont)
        {

            try
            {
                //Chamando o método Atualizar da OntRepositorio
                if (ModelState.IsValid)
                {
                    _ontRepositorio.Atualizar(ont);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                //Comando para forçar o return view cair na view de editar, porque não existe uma view com o nome Alterar, existe com o nome Editar
                return View("Editar", ont);
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos editar seu produto, tente novamente, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
}
}

ControleEstoque/Controllers/W5Controller.cs
using ControleEstoque.Filters;
using ControleEstoque.Models;
using ControleEstoque.Repositorio;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace ControleEstoque.Controllers
{
    //Função para ativar o filtro e diferenciar se é um usuario padrão ou admin e colocar suas restrições
    [PaginaParaUsuarioLogado]
    public class W5Controller : Controller
    {
        private readonly IW5Repositorio _w5Repositorio;
        public W5Controller(IW5Repositorio w5Repositorio)
        {
            _w5Repositorio = w5Repositorio;
        }
        public IActionResult Index() 
        {
            List<W5Model> W5s = _w5Repositorio.Buscartodos();
            return View(W5s);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            W5Model w5= _w5Repositorio.ListarPorId(id);
            return View(w5);
        }

        public IActionResult detalhes(int id)
        {
            W5Model w5= _w5Repositorio.ListarPorId(id);
            return View(w5);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            W5Model w5= _w5Repositorio.ListarPorId(id);
            return View(w5);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                //Chamando o método Apagar da OntRepositorio
                bool apagado = _w5Repositorio.Apagar(id);

                if(apagado)
                {
                    TempData["MensagemSucesso"] = "Produto apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu produto!";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu produto, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(W5Model w5)
        {
            //Chamando o método Adicionar da OntRepositorio

            try
            {
                if (ModelState.IsValid)
                {
                    _w5Repositorio.Adicionar(w5);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(w5);
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu produto, tente novamente, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
         
        }

        [HttpPost]
        public IActionResult Alterar(W5Model w5)
        {

            try
            {
                //Chamando o método Atualizar da OntRepositorio
                if (ModelState.IsValid)
                {
                    _w5Repositorio.Atualizar(w5);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                //Comando para forçar o return view cair na view de editar, porque não existe uma view com o nome Alterar, existe com o nome Editar
                return View("Editar", w5);
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos editar seu produto, tente novamente, detalhe do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
}
}

ControleEstoque/Views/W5/ApagarConfirmacao.cshtml
@model W5Model
@{
    ViewData["Title"] = "Confirmação apagar produtos";
}

<div class="text-center">
    <h3>Realmente deseja apagar o produto (@Model.Nome) ?</h3>
</div>

<a class="btn btn-primary" role="button" asp-controller="W5" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" btn-block role="button" asp-controller="W5" asp-route-id="@Model.Id" asp-action="Apagar">Confirmar exclusão</a>

ControleEstoque/Views/W5/Criar.cshtml
@model W5Model

@{
    ViewData["Title"] = "Cadastro de produtos";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar produto</h1>
</div>

<form asp-controller="W5" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="mac">Mac</label>
        <input type="text" asp-for="Mac" class="form-control" placeholder="Digite o mac do produto">
        @Html.ValidationMessageFor(x => x.Mac)
    </div>

    <div class="form-group">
        <label for="serie">Numero de serie</label>
        <input type="text" asp-for="NumeroSerie" class="form-control" placeholder="Digite o numero de série do produto">
        @Html.ValidationMessageFor(x => x.NumeroSerie)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="W5" asp-action="Index" role="button">Voltar</a>
</form>

ControleEstoque/Views/W5/Detalhes.cshtml
@model W5Model
@{
    ViewData["Title"] = "Detalhes do produto";
}

<head>
    <link rel="stylesheet" href="~/css/Ont.css" asp-append-version="true" />
</head>

<div class="text-center">

    <h2 class="display-4 Titulo_detalhes">Detalhes sobre W5 @Model.Nome</h2>

</div>

<br/>
<br />
<br />
    <div class="central-Detalhes">

    <div class="fundo_detalhes">
    <div class="form-group">
        <label for="nome">Nome: @Model.Nome</label>

    </div>
    <br/>
    <div class="form-group">
        <label for="mac">Mac: @Model.Mac</label>      
    </div>
    <br/>
    <div class="form-group">
        <label for="NumeroSerie">Número de série: @Model.NumeroSerie</label>   
    </div>
 
    </div>

    </div>
    <br/>
    <br/>
<a class="btn btn-secondary botao-Detalhes" asp-controller="W5" asp-action="Index" role="button">Voltar</a>

ControleEstoque/Views/W5/Editar.cshtml
@model W5Model

@{
    ViewData["Title"] = "Editar produtos";
}

<div class="text-center">
    <h1 class="display-4">Editar produto</h1>
</div>

<form asp-controller="W5" asp-action="Alterar" method="post">

    @* Filtaro ID porem não ha necessidade de exibi-lo, mas precisa chama-lo na View para o botão de alterar funcionar *@
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="mac">Mac</label>
        <input type="text" asp-for="Mac" class="form-control" placeholder="Digite o mac do produto">
        @Html.ValidationMessageFor(x => x.Mac)
    </div>

    <div class="form-group">
        <label for="serie">Numero de serie</label>
        <input type="text" asp-for="NumeroSerie" class="form-control" placeholder="Digite o numero de série do produto">
        @Html.ValidationMessageFor(x => x.NumeroSerie)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="W5" asp-action="Index" role="button">Voltar</a>
</form>

ControleEstoque/Views/W5/Index.cshtml
@model List<W5Model>
@{
    ViewData["Title"] = "Listagem de produtos";
}

<head>
    <link rel="stylesheet" href="~/css/Ont.css" asp-append-version="true" />
</head>

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-success" role="button" asp-controller="W5" asp-action="Criar">Adicionar novo produto</a>
    </div>
    <br/>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
    </div>
    }

    <br/>

    <h1 class="display-4 Titulo_ont">Listagem de W5</h1>



   @*<div class="container-fluid">
        <div class="row justify-content-center">
            @if (Model != null && Model.Any())
            {
                foreach (OntModel ont in Model)
                {
                    <div class="col-md-4">
                        <div class="card m-2" style="background-color:#212529;">
                            <img class="card-img-top" src="~/Imagens/intelbras-WiFiber-121-AC-Wi-Force-Router-Featured-Image-1.jpg" alt="ONT INTELBRAS" height="200px">
                        <div class="card-body">
                            <h5 class="card-title nome" style="margin-bottom:20px;">@ont.Nome</h5>
                            <a role="button" class="btn btn-primary me-1" asp-route-id="@ont.Id" asp-asp-controller="Ont" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@ont.Id" asp-asp-controller="Ont" asp-action="ApagarConfirmacao">Apagar</a>
                            <a role="button" class="btn btn-success" asp-route-id="@ont.Id" asp-asp-controller="Ont" asp-action="Detalhes">Detalhes</a>
                        </div>
                    </div>
                        
                     </div>


                    
                }
            }
        </div>
    </div> *@








    



   <table class="display" id="table-ont" style="width:100%;">
        <thead>
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">Mac</th>
                <th scope="col" class="text-center">Número de Série</th>
                <th scope="col" class="text-center">Data de Cadastro</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (W5Model w5 in Model)
                {
                    <tr>
                        <th scope="row">@w5.Id</th>
                        <td>@w5.Nome</td>
                        <td>@w5.Mac</td>
                        <td>@w5.NumeroSerie</td>
                        <td>@w5.DataCadastro</td>
                        <td>
                            <div class="btn-group gap-3" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@w5.Id" asp-controller="W5" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@w5.Id" asp-controller="W5" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>